
version: "3.8"
services:
  flask-app:
    container_name: hw3-container_flask-app
    build:
      context: .
      dockerfile: Dockerfile-dev
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - .:/app



